FROM php:apache-bullseye

# composer install
COPY --from=composer:2.2 /usr/bin/composer /usr/bin/composer

COPY php.ini /usr/local/etc/php/php.ini
COPY init.sh /tmp/init.sh

RUN apt-get update && apt-get install -y zip git libzip-dev
RUN docker-php-ext-install pdo_mysql
RUN a2enmod rewrite

WORKDIR /var/www/html

RUN chmod -R 777 /tmp/init.sh

CMD ["/bin/bash", "-c", "/tmp/init.sh"] 